### PR TITLE
Support for external storage and bug fixes

### PR DESCRIPTION
**Pull request by chrros95**
In issue #34 @z0ow pointed to an issue with the owner of the file. My investigations showed that the root cause for the exceptions is, that files on external storage never have an owner. To allow finding duplicates on external storage as well, I've implemented a fallback mechanism. This mechanism provides the ability to show the duplicate to each user that has access to that files.
Detecting duplicates on external storage may cause additional costs for data transfer, as this might need to be avoided scanning can be is abled by changing the config `./occ config:app:set --value=true duplicatefinder ignore_mounted_files`.

Furthermore, this PR changes the event on which the detection works while scanning to _postScanFile_. After this event, a file in the cache with a higher probability than after the _scanFile_ event. That should reduce the number of NotFoundExceptions and provided a solution for #37

### CODE REVIEW

**Comment by PaulLereverend** [comment]
Hi Christian 
I found a issue on this PR. Running this version on my test instance showed this :
image
There is only one file on both case but it is showed as duplicate. I don't know why

**Comment by chrros95** [comment]
Thanks for testing.
I have an idea what might be the problem - did the issue occurred on an instance on which the app has been upgraded through version 0.0.9?

**Comment by PaulLereverend** [comment]
No, the app was updated from the current version (0.0.11).

**Comment by chrros95** [comment]
Sorry for the delayed response.
Can you please try the latest commits?
After running `./occ maintenance:repair` again, everything should be fine.

**Comment by PaulLereverend** [comment]
Don't be sorry, we are all doing this on our free time 😉 

After pulling and running the repair I got this weird behavior : 
image

I fixed this by running the `clear` and the `find-all` command. Wouldn't it be a good idea to perform a clear and a find on each update of the app ? 
Otherwise everything else is working fine.

**Comment by chrros95** [comment]
First, this was kind of strange because the issue was only replicable sometimes - like it's a timing problem or so.
But with the new test case, the issue was replicated reliably.
 
As a workaround the all files will be removed to provide the UI and the CLI  a hint that this is not a real duplicate. First I thought about removing the duplicate completely from the list, but this would have cause a huge problem with the pagination.
The UI already handled duplicates with no files probably but the CLI hasn't such a mechanism, so only there is a change.

**Comment by chrros95** [comment]
Sorry, I forgot to answer your question.
Indeed, it would be much easier to clear all records after an upgrade. But, this would mean that all hashes need to be recalculated which can require a lot of resources depending on the number of files and the file sizes. To avoid this I would like to spend as much time on the development of migrations until it there is no other way to do this.

**Comment by PaulLereverend** [comment]
You are right about the resources consumption. 

I tested your last changes and the list is now displayed like this : 
image

It might be caused by this error : 
```
jQuery.Deferred exception: groupItems.forEach is not a function TypeError: groupItems.forEach is not a function
    at getGroupElement (http://localhost:9000/apps/duplicatefinder/js/script.js?v=1f31c3a5-0:118:16)
    at http://localhost:9000/apps/duplicatefinder/js/script.js?v=1f31c3a5-0:25:24
    at Array.forEach (<anonymous>)
    at render (http://localhost:9000/apps/duplicatefinder/js/script.js?v=1f31c3a5-0:24:13)
    at Object.<anonymous> (http://localhost:9000/apps/duplicatefinder/js/script.js?v=1f31c3a5-0:245:7)
    at u (http://localhost:9000/core/js/dist/main.js?v=1f31c3a5-0:25:25700)
    at c (http://localhost:9000/core/js/dist/main.js?v=1f31c3a5-0:25:26002) undefined
```

**Comment by chrros95** [comment]
So, I was not able to replicate the issue fully. But based on the error you showed, I've added an additional javascript check and changed the pagination to avoid this situation.
Can you please give it another try?

If the issue persists, I would like to please you to take a look at the CLI `./occ duplicates:list` to show whether there is an issue as well.

**Comment by PaulLereverend** [comment]
Looks good ! No more issues 😃

**Pull request merged**
