### PR TITLE
Add a list of action icons to each element.

### PR DESCRIPTION
**Pull request by miceno**
Add actions to each element.

* Show file: it will redirect to the show file page.
* Show details: it will redirect to the file details.

Solves #3

### CODE REVIEW

**Comment by miceno** [comment]
Hi @PaulLereverend 

Will you please advice on this?

Thank you!

**Comment by miceno** [comment]
Sorry for insisting, but will you please advice on this? @PaulLereverend

**Comment by PaulLereverend** [comment]
Sorry for the delay 
Thank you very much 🚀

**Comment by miceno** [comment]
@water-man 
I know features do always need improvements, but it might be that other users might find interesting opening the link in the same window, and there is a quick fix for your improvement: use your browser feature to "Open in new tab".

On the contrary, if the feature will force every link to open in a new tab, users that will prefer to open them on the same tab will not have that feature, they will request it and they have no quick fix on the browser.

**Comment by miceno** [comment]
@water-man On the issue of the spinning wheel, you are right! I didn't test it throughly.

Feel free to create a PR and improve the improvement 👍

**Pull request merged**
